version: '3'
services:
  librairy-keywords:
    image: librairy/keywords:0.1
  search-api:
     image: librairy/search-api:1.3.0
     ports:
      - "8080:7777"
     environment:
       - LIBRAIRY_API_USERNAME=oeg
       - LIBRAIRY_API_PASSWORD=oeg2018
       - LIBRAIRY_API_ENDPOINT=http://librairy.linkeddata.es/api
       - KEYWORD_ENDPOINT=http://librairy-keywords:5000/nlp/keywords
       - MODEL_ENDPOINT=http://librairy.linkeddata.es/jrc-%%-model
       - SOLR_ENDPOINT=http://librairy.linkeddata.es/data/tbfy
       - REST_PATH=/search-api
