version: '3'
services:
  nlp:
    image: librairy/nlp:1.3
    environment:
      - REST_PATH=/
      - JAVA_OPTS=-Xmx1024m
  jrc-en-model:
    image: librairy/jrc-en-model:1.3
    ports:
     - "8085:7777"
    environment:
      - REST_PATH=/
      - NLP_ENDPOINT=nlp
      - JAVA_OPTS=-Xmx128m
  jrc-es-model:
    image: librairy/jrc-es-model:1.3
    ports:
     - "8086:7777"
    environment:
      - REST_PATH=/
      - NLP_ENDPOINT=nlp
      - JAVA_OPTS=-Xmx128m
  jrc-fr-model:
    image: librairy/jrc-fr-model:1.3
    ports:
     - "8087:7777"
    environment:
      - REST_PATH=/
      - NLP_ENDPOINT=nlp
      - JAVA_OPTS=-Xmx128m
  jrc-de-model:
    image: librairy/jrc-de-model:1.3
    ports:
     - "8088:7777"
    environment:
      - REST_PATH=/
      - NLP_ENDPOINT=nlp
      - JAVA_OPTS=-Xmx128m
  solr:
    image: solr:7.7
    ports:
     - "8983:8983"
    volumes:
      - ./target/solr-data:/opt/solr/server/solr/mycores
      - ./src/main/banana:/opt/solr/server/solr-webapp/webapp/banana
    entrypoint:
      - docker-entrypoint.sh
      - solr-precreate
      - documents
    environment:
      - SOLR_JAVA_MEM=-Xms512m -Xmx512m
  librairy-api:
    image: librairy/api:latest
    ports:
     - "8081:7777"
    environment:
      - LIBRAIRY_API_USERS=oeg:oeg2018
      - JAVA_OPTS=-Xmx128m
      - REST_PATH=/librairy-api
    volumes:
     - ./tmp:/librairy
     - /var/run/docker.sock:/var/run/docker.sock
  search-api:
     image: librairy/search-api:1.0
     ports:
      - "8080:7777"
     environment:
       - LIBRAIRY_API_USERNAME=oeg
       - LIBRAIRY_API_PASSWORD=oeg2018
       - LIBRAIRY_API_ENDPOINT=http://librairy-api:7777/librairy-api
       - MODEL_ENDPOINT=http://jrc-%%-model:7777
       - SOLR_ENDPOINT=http://solr:8983/solr/documents
       - JAVA_OPTS=-Xmx128m
       - REST_PATH=/search-api
